app :
  appName: "My Clean Architecture (develop)"
  domain: "Core"
  httpPort: 8080
public:
    - "api/signin"
dbConfig:
  host: 127.0.0.1
  port: 5432
  dbName: test
  username: postgres
  password: 1234
readDbConfig:
  host: 127.0.0.1
  port: 5432
  dbName: test
  username: postgres
  password: 1234