app :
  appName: "My Clean Architecture (develop)"
  domain: "Core"
  httpPort: 8080
public:
    - "api/signin"
dbConfig:
  host: 127.0.0.1
  port: 5432
  dbName: test
  username: postgres
  password: 1234
readDbConfig:
  host: 127.0.0.1
  port: 5432
  dbName: test
  username: postgres
  password: 1234
redisConfig:
  host: 192.168.1.225
  port: 6379
  password:
  db: 0
  protocol: 2
service:
  pgwUrl: http://localhost:8083/api/master-data/service-provider-method
  qrPayUrl: